[workspace]

resolver = "2"

members = ["context"]

[workspace.dependencies]
init = { git = "https://github.com/RustyYato/init.git", branch = "main" }
bumpme = { git = "https://github.com/RustyYato/bumpme.git", branch = "main" }

rustc-hash = "1"
