[package]
name = "context"
version = "0.1.0"
edition = "2021"

[dependencies]
init.workspace = true
bumpme.workspace = true
rustc-hash.workspace = true
hashbrown.workspace = true
istr.workspace = true
